apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redemption-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redemption-secrets
    creationPolicy: Owner
  data:
    - secretKey: sentry-dsn
      remoteRef:
        key: redemption/sentry
        property: dsn
    - secretKey: rds-host
      remoteRef:
        key: redemption/production/rds
        property: host
    - secretKey: rds-password
      remoteRef:
        key: redemption/production/rds
        property: password
    - secretKey: redis-url
      remoteRef:
        key: redemption/production/cache
        property: url
