apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redemption
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "REPLACE_WITH_ACM_CERT_ARN"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/wafv2-acl-arn: "REPLACE_WITH_WAF_ARN"
spec:
  ingressClassName: alb
  rules:
    - host: redemption.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redemption
                port:
                  name: http
