apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redemption-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redemption-worker
  minReplicaCount: 2
  maxReplicaCount: 8
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-sqs-trigger-auth
      metadata:
        queueLength: "100"
        awsRegion: "ap-southeast-1"
        identityOwner: operator
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
