apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: redemption
spec:
  template:
    spec:
      containers:
        - name: redemption
          env:
            - name: DD_ENV
              value: production
            - name: SENTRY_ENVIRONMENT
              value: production
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: redemption
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: redemption
